# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: CME 213 / ME 339
subtitle: Website for Stanford CME 213 / ME 339
email: darve@stanford.edu
author: Eric Darve
description: >- # this means to ignore newlines until "baseurl:"
  Introduction to parallel computing using MPI, openMP, and CUDA
baseurl: /cme213-spring-2021
simple_search: http://google.com/search
name: cme213-spring-2021
markdown_ext: "markdown,mkdown,mkdn,mkd,md"
timezone: America/Los_Angeles
excerpt_separator: <!--more-->  # you can specify your own separator, of course.
markdown: kramdown

post:
  template: _post.txt
  extension: md

page:
  template: _page.txt
  extension: md

git:
  branch: main

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
exclude:
   - README.md
   - .sass-cache/
   - .jekyll-cache/
   - gemfiles/
   - Gemfile
   - Gemfile.lock
   - node_modules/